spring:
  datasource:
    username: "postgres"
    password: "qwerty"
    url: "jdbc:postgresql://127.0.0.1:5432/BookingGame"
    driver-class: "org.postgresql.Driver"
jpa:
  show-sql: true
  hibernate:
    ddl-auto: create-drop