spring:
  datasource:
    username: "postgres"
    password: "qwerty"
    url: "jdbc:postgresql://127.0.0.1:5432/BookingGame"
    driver-class-name: "org.postgresql.Driver"

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  liquibase:
    change-log: classpath:changelog-master.xml
    url: jdbc:postgresql://127.0.0.1:5432/BookingGame
    user: postgres
    password: qwerty
 

